sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: skyLX
    username: root
    password: qwert123

  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucket-name: lxsky
    region: cn-beijing